### ISSUE TITLE
many to many relationship

### ISSUE THREAD

**Issue by asadghazanfary** [freshbitsweb/laravel-relationships-data#1]
hi @gauravmak 

can i use 4 foreign key in middle table in many to many relationship?

for example:

users table =>
id
name
email

languages table =>
id
name

fields table =>
id
name

field_language_user_table => middle table
field_id
user_id
from_language
to_language

**Comment by gauravmak** [comment]
Technically, you can have as many foreign keys as you want in a table.

But, the many-to-many relationship that you define involves only the 2 of the foreign keys in the pivot table and other columns are not considered directly by the framework while playing with the relationship.

Does this answer your question?

**Comment by asadghazanfary** [comment]
thank's for answer.

> But, the many-to-many relationship that you define involves only the 2 of the foreign keys in the pivot table and other columns are not considered directly by the framework while playing with the relationship.

What solution would you suggest?

**Comment by gauravmak** [comment]
What do you want to accomplish?

**Comment by asadghazanfary** [comment]
i want create many to many relationship.

My pivot table is designed this way:

            $table->unsignedBigInteger('user_id');
            $table->unsignedBigInteger('field_id');
            $table->unsignedBigInteger('from_language');
            $table->unsignedBigInteger('to_language');
            $table->enum('level', [1, 2, 3]);
            $table->boolean('is_special')->default(0);
            $table->boolean('approved')->default(0);
            $table->boolean('active')->nullable();

            $table->primary(['user_id', 'field_id', 'from_language', 'to_language']);

            $table->foreign('user_id')->references('id')->on('users');
            $table->foreign('field_id')->references('id')->on('fields');
            $table->foreign('from_language')->references('id')->on('languages');
            $table->foreign('to_language')->references('id')->on('languages');

**Comment by gauravmak** [comment]
As far as I know, the Many-to-many relationship is possible between 2 tables + 1 pivot table only.

You may want to create multiple one-to-many relationships among your models.

**Comment by asadghazanfary** [comment]
i think the link can i help me

[https://laravel.com/docs/6.x/eloquent-relationships#defining-custom-intermediate-table-models](url)

**Comment by gauravmak** [comment]
Yes, as I mentioned, you can add any number of 'other' columns in the pivot table but that are not considered for the many-to-many relationship.

If you can share how do you exactly want to fetch/save data, I may be able to help.
